### ISSUE TITLE
After using SDWebImage library application rejected from app store

### ISSUE THREAD

**Issue by rishabh14augshukla** [xamarin/XamarinComponents#601] opened 2019-06-21 14:51 UTC
Hi all

I am using SDWebImage library (4.4.0) in Xamarin tvOS project and it is working fine and when I  uploaded my application on App Store then App Store rejected my application and gives the error **ITMS-90496: Invalid Executable - The executable 'XYZ.tvOS.app/XYZ.tvOS' does not contain bitcode** .

Please look into it. What is the main issue in this library? Why I am not able to deploy my application on the App Store after using this library in Xamarin tvOS.

**Comment by newky2k** [comment] 2019-06-24 17:03
@rishabh14augshukla We are working on an update to SDWebImage 5.0.2 which should contain the relavant bitcode #589

**Comment by rishabh14augshukla** [comment] 2019-06-25 20:43
@newky2k Please let me know when you are going to launch SDWebImage 5.0.2 library. or meanwhile do you have any solution for me.

**Comment by newky2k** [comment] 2019-06-27 21:05
@rishabh14augshukla  i'm working on it ATM but there are some big differences to the previous version  so the build needs some tweaking.

**Comment by rishabh14augshukla** [comment] 2019-06-28 14:39
@newky2k Can you please tell me when you are going to launch a new library version (5.0.2 or etc).
Currently, in Xamarin the latest version of the library is 4.4

**Comment by newky2k** [comment] 2019-07-02 20:20
@rishabh14augshukla  The new 5.x version of SDWebImage is substantially different, so I've gone back and checked the .a files included in the current tvos dll and both of them include bitcode.

It turns out that SDWebImage include tvOS support and bitcode in October 2015

**Comment by rishabh14augshukla** [comment] 2019-07-09 15:22
@newky2k When I use SDWebImage library in Xamarin tvOS then it is working fine. There is no issue of the working but when I uploaded my build on app store then it gives me an error message "**ITMS-90496: Invalid Executable - The executable 'XYZ.tvOS.app/XYZ.tvOS' does not contain bitcode** ." 
If I remove this library then app store is accepting my build.

Please tell me if I am doing wrong anything.

**Comment by newky2k** [comment] 2019-07-09 21:15
@rishabh14augshukla  ok let me try and replicate it and go from there.  What options are you using to publish and sign the archive?  are you doing it from Visual Studio on the mac?

**Comment by rishabh14augshukla** [comment] 2019-07-12 11:54
@newky2k I am using Xamarin tvOS and using the Visual Studio(2017) on the mac. To create .ipa file, I am using the archive option. With the help of archive, I am creating a .ipa file. 

That .ipa file I am uploading on the app store using Application Loader.

Please let me know if you need anything from the end. Please provide a solution.

**Comment by rishabh14augshukla** [comment] 2019-07-12 12:32
@newky2k  Also I notice one thing when I do not use this library then .ipa size is around 450 MB and after using this library size is also reducing like 25 - 30 MB. 

If possible then we can connect also for more details.

**Comment by rishabh14augshukla** [comment] 2019-07-19 11:22
@newky2k Please reply on it.

**Comment by newky2k** [comment] 2019-07-19 15:41
@rishabh14augshukla I'm looking into this for you still, its odd that it becomes smaller after you add it, which seems to suggest that something is being removed

**Comment by rishabh14augshukla** [comment] 2019-08-09 15:34
@newky2k Did you get a chance to look at it? Please help me out.

**Comment by rishabh14augshukla** [comment] 2019-08-20 14:48
@newky2k Please reply on it.

**Comment by newky2k** [comment] 2019-08-20 17:42
@rishabh14augshukla  Sorry but i have been unable to find the cause of this issue.

**Comment by rishabh14augshukla** [comment] 2019-08-27 13:59
@newky2k  If you want then Can we connect ?
I can show you how to repo this issue

**Comment by SotoiGhost** [comment] 2019-09-11 19:31
@rishabh14augshukla I'll continue the thread on #593 as it seems to be a duplicate of this. Best!

**Closed as completed by SotoiGhost** 2019-09-11 19:31 UTC
Labels: needs-info
