### ISSUE TITLE
Card.io for Android  doesn't work on v 7.1

### ISSUE THREAD

**Issue by ysavit** [xamarin/XamarinComponents#204] opened 2017-08-04 21:34 UTC
I compiled and run sample project on my sumsung s8 with **v7.1** - doesn't work. Card is not parsed
Tried on older Marshmallow phone. Works fine.
 Any idea why?

**Comment by newky2k** [comment] 2018-07-24 19:21
@ysavit  Can you try on the current version and see if the issue is still there?

**Comment by newky2k** [comment] 2018-08-07 16:41
Closed as no further information after two weeks

**Closed as completed by newky2k** 2018-08-07 16:41 UTC
Labels: needs-info
